# Generated by Django 4.2.2 on 2023-08-12 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(null=True, upload_to='images/profile')),
                ('owner_name', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=200)),
                ('whatsapp_no', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('established_year', models.IntegerField(null=True)),
                ('no_of_employees', models.IntegerField(null=True)),
                ('manager_name', models.CharField(max_length=250)),
                ('manager_contact_no', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PublicInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restorant_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=300, null=True)),
                ('contact_no', models.CharField(max_length=200, null=True)),
                ('whatsapp_no', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('private_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfileSetup.privateinformation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingTimeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_time', models.CharField(max_length=100, null=True)),
                ('public_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfileSetup.publicinformation')),
            ],
        ),
        migrations.CreateModel(
            name='SettlementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('private_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfileSetup.privateinformation')),
            ],
        ),
        migrations.CreateModel(
            name='SettlementMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('private_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfileSetup.privateinformation')),
            ],
        ),
        migrations.CreateModel(
            name='RestorantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(null=True, upload_to='images/restorant')),
                ('public_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfileSetup.publicinformation')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('private_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfileSetup.privateinformation')),
            ],
        ),
        migrations.CreateModel(
            name='OrderOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('public_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfileSetup.publicinformation')),
            ],
        ),
    ]
