# Generated by Django 4.2.2 on 2023-10-08 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('super_admin', models.IntegerField()),
                ('profile', models.ImageField(null=True, upload_to='images/profile/')),
                ('owner_name', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=200)),
                ('whatsapp_no', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('established_year', models.IntegerField(null=True)),
                ('no_of_employees', models.IntegerField(null=True)),
                ('manager_name', models.CharField(max_length=250)),
                ('manager_contact_no', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('is_active', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PublicInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('super_admin', models.IntegerField()),
                ('restorant_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=300, null=True)),
                ('contact_no', models.CharField(max_length=200, null=True)),
                ('whatsapp_no', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('private_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfileSetup.privateinformation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingTimeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_time', models.IntegerField(null=True)),
                ('public_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfileSetup.publicinformation')),
            ],
        ),
        migrations.CreateModel(
            name='SettlementTypeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_type', models.IntegerField(null=True)),
                ('private_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfileSetup.privateinformation')),
            ],
        ),
        migrations.CreateModel(
            name='SettlementModeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_mode', models.IntegerField(null=True)),
                ('private_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfileSetup.privateinformation')),
            ],
        ),
        migrations.CreateModel(
            name='RestorantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(null=True, upload_to='images/restorant/')),
                ('public_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfileSetup.publicinformation')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentOptionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_option', models.IntegerField(null=True)),
                ('private_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfileSetup.privateinformation')),
            ],
        ),
        migrations.CreateModel(
            name='OrderOptionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_option', models.IntegerField(null=True)),
                ('public_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfileSetup.publicinformation')),
            ],
        ),
    ]
