# Generated by Django 4.2.2 on 2023-10-21 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_addons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addons',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/addons'),
        ),
        migrations.CreateModel(
            name='FoodItemAddons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.addons')),
                ('foodItems', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.fooditems')),
            ],
        ),
    ]
