# Generated by Django 4.2.2 on 2023-10-08 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Menu', '0001_initial'),
        ('DelivaryBoys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_reference', models.CharField(max_length=100, null=True)),
                ('customer_name', models.CharField(max_length=200, null=True)),
                ('customer_address', models.TextField(null=True)),
                ('customer_email', models.CharField(max_length=200, null=True)),
                ('customer_mobile', models.CharField(max_length=200, null=True)),
                ('customer_balance', models.FloatField()),
                ('order_date', models.DateField(null=True)),
                ('order_time', models.TimeField(null=True)),
                ('confirm_status', models.IntegerField(null=True)),
                ('delivary_status', models.CharField(max_length=200, null=True)),
                ('delivary_boy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DelivaryBoys.delivaryboy')),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.orderstatus')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, null=True)),
                ('item_description', models.TextField(null=True)),
                ('item_price', models.FloatField(null=True)),
                ('item_quantity', models.FloatField(null=True)),
                ('total_price', models.FloatField(null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.fooditems')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.orders')),
            ],
        ),
    ]
